function [RunNumber,targetDiskPos_percent,targetConePos_percent,NominalNfan_RPM,Nmotor_RPM,Nfan_instantaneous_RPM,Nfan_RPM,Tq_lb,Ps2L_wg,deltaPs2_5_2L_wg,Ps2_5L_wg,Ps7L_wg,Ps5L_wg,deltaPs5_6L_wg,Ps6L_wg,T2_5aL_F,T2_5bL_F,T2_5cL_F,T7aL_F,T7bL_F,T7cL_F,Trtd7L_F,T5aL_F,T5bL_F,T5cL_F,Trtd5L_F,T6aL_F,T6bL_F,T6cL_F,Trtd6L_F,Pba_mbar,Pbb_mbar,Pbc_mbar,Ps0_wg,T0a_F,T0b_F,T0c_F,Tdewa_F,Tdewb_F,Tdewc_F,Rha_percent,Rhb_percent,Rhc_percent,DLC_in,DL0_in,DL45_in,DL90_in,DL135_in,DL180_in,DL225_in,DL270_in,DL315_in,EFanPitch_deg,DiskPos_percent,ConePos_percent] = importFanData(filename, startRow, endRow)
%   [RunNumber,targetDiskPos_percent,targetConePos_percent,NominalNfan_RPM,Nmotor_RPM,Nfan_instantaneous_RPM,Nfan_RPM,Tq_lb,Ps2L_wg,deltaPs2_5_2L_wg,Ps2_5L_wg,Ps7L_wg,Ps5L_wg,deltaPs5_6L_wg,Ps6L_wg,T2_5aL_F,T2_5bL_F,T2_5cL_F,T7aL_F,T7bL_F,T7cL_F,Trtd7L_F,T5aL_F,T5bL_F,T5cL_F,Trtd5L_F,T6aL_F,T6bL_F,T6cL_F,Trtd6L_F,Pba_mbar,Pbb_mbar,Pbc_mbar,Ps0_wg,T0a_F,T0b_F,T0c_F,Tdewa_F,Tdewb_F,Tdewc_F,Rha_percent,Rhb_percent,RHc_percent,DLC_in,DL0_in,DL45_in,DL90_in,DL135_in,DL180_in,DL225_in,DL270_in,DL315_in,EFanPitch_deg,DiskPos_percent,ConePos_percent]
%   = importFanData(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [RunNumber,targetDiskPos_percent,targetConePos_percent,NominalNfan_RPM,Nmotor_RPM,Nfan_instantaneous_RPM,Nfan_RPM,Tq_lb,Ps2L_wg,deltaPs2_5_2L_wg,Ps2_5L_wg,Ps7L_wg,Ps5L_wg,deltaPs5_6L_wg,Ps6L_wg,T2_5aL_F,T2_5bL_F,T2_5cL_F,T7aL_F,T7bL_F,T7cL_F,Trtd7L_F,T5aL_F,T5bL_F,T5cL_F,Trtd5L_F,T6aL_F,T6bL_F,T6cL_F,Trtd6L_F,Pba_mbar,Pbb_mbar,Pbc_mbar,Ps0_wg,T0a_F,T0b_F,T0c_F,Tdewa_F,Tdewb_F,Tdewc_F,Rha_percent,Rhb_percent,RHc_percent,DLC_in,DL0_in,DL45_in,DL90_in,DL135_in,DL180_in,DL225_in,DL270_in,DL315_in,EFanPitch_deg,DiskPos_percent,ConePos_percent] = importFanData('03300AFCA_A.txt',1, 35);
%

% Auto-generated by MATLAB on 2019/07/10 09:25:18

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
RunNumber = dataArray{:, 1};
targetDiskPos_percent = dataArray{:, 2};
targetConePos_percent = dataArray{:, 3};
NominalNfan_RPM = dataArray{:, 4};
Nmotor_RPM = dataArray{:, 5};
Nfan_instantaneous_RPM = dataArray{:, 6};
Nfan_RPM = dataArray{:, 7};
Tq_lb = dataArray{:, 8};
Ps2L_wg = dataArray{:, 9};
deltaPs2_5_2L_wg = dataArray{:, 10};
Ps2_5L_wg = dataArray{:, 11};
Ps7L_wg = dataArray{:, 12};
Ps5L_wg = dataArray{:, 13};
deltaPs5_6L_wg = dataArray{:, 14};
Ps6L_wg = dataArray{:, 15};
T2_5aL_F = dataArray{:, 16};
T2_5bL_F = dataArray{:, 17};
T2_5cL_F = dataArray{:, 18};
T7aL_F = dataArray{:, 19};
T7bL_F = dataArray{:, 20};
T7cL_F = dataArray{:, 21};
Trtd7L_F = dataArray{:, 22};
T5aL_F = dataArray{:, 23};
T5bL_F = dataArray{:, 24};
T5cL_F = dataArray{:, 25};
Trtd5L_F = dataArray{:, 26};
T6aL_F = dataArray{:, 27};
T6bL_F = dataArray{:, 28};
T6cL_F = dataArray{:, 29};
Trtd6L_F = dataArray{:, 30};
Pba_mbar = dataArray{:, 31};
Pbb_mbar = dataArray{:, 32};
Pbc_mbar = dataArray{:, 33};
Ps0_wg = dataArray{:, 34};
T0a_F = dataArray{:, 35};
T0b_F = dataArray{:, 36};
T0c_F = dataArray{:, 37};
Tdewa_F = dataArray{:, 38};
Tdewb_F = dataArray{:, 39};
Tdewc_F = dataArray{:, 40};
Rha_percent = dataArray{:, 41};
Rhb_percent = dataArray{:, 42};
Rhc_percent = dataArray{:, 43};
DLC_in = dataArray{:, 44};
DL0_in = dataArray{:, 45};
DL45_in = dataArray{:, 46};
DL90_in = dataArray{:, 47};
DL135_in = dataArray{:, 48}; 
DL180_in = dataArray{:, 49};
DL225_in = dataArray{:, 50};
DL270_in = dataArray{:, 51};
DL315_in = dataArray{:, 52};
EFanPitch_deg = dataArray{:, 53};
DiskPos_percent = dataArray{:, 54};
ConePos_percent = dataArray{:, 55};
save('testData', 'RunNumber','targetDiskPos_percent','targetConePos_percent','NominalNfan_RPM','Nmotor_RPM','Nfan_instantaneous_RPM','Nfan_RPM','Tq_lb','Ps2L_wg','deltaPs2_5_2L_wg','Ps2_5L_wg','Ps7L_wg','Ps5L_wg','deltaPs5_6L_wg','Ps6L_wg','T2_5aL_F','T2_5bL_F','T2_5cL_F','T7aL_F','T7bL_F','T7cL_F','Trtd7L_F','T5aL_F','T5bL_F','T5cL_F','Trtd5L_F','T6aL_F','T6bL_F','T6cL_F','Trtd6L_F','Pba_mbar','Pbb_mbar','Pbc_mbar','Ps0_wg','T0a_F','T0b_F','T0c_F','Tdewa_F','Tdewb_F','Tdewc_F','Rha_percent','Rhb_percent','Rhc_percent','DLC_in','DL0_in','DL45_in','DL90_in','DL135_in','DL180_in','DL225_in','DL270_in','DL315_in','EFanPitch_deg','DiskPos_percent','ConePos_percent');
end

